#!/usr/bin/env python3
"""Fetch Swiss mountain webcams from the Windy Webcams API v3.

Writes results to docs/prototypes/webcams_windy_data.js as a JS global
(`window.WINDY_WEBCAMS`), so the prototype page can load it via a
<script> tag (no fetch — works under file://).

The API key must be supplied via the WINDY_API_KEY env var. Never commit it.

Usage:
    WINDY_API_KEY=xxxxx python scripts/fetch_windy_webcams.py
"""

import json
import os
import sys
import urllib.parse
import urllib.request
from pathlib import Path

API_URL = "https://api.windy.com/webcams/api/v3/webcams"
# Center of Switzerland, ~150 km radius covers the whole country plus a buffer.
NEARBY = "46.85,8.5,150"
CATEGORIES = "mountain"
PAGE_LIMIT = 50  # max allowed per request on the free tier
MAX_PAGES = 6    # up to 300 candidate cams; we filter down after
MIN_VIEWS = 1000  # filter out very low-traffic cams (often dead/private)

OUTPUT = (
    Path(__file__).resolve().parent.parent
    / "docs" / "prototypes" / "webcams_windy_data.js"
)


def fetch_page(key: str, offset: int) -> dict:
    params = {
        "nearby": NEARBY,
        "categories": CATEGORIES,
        "include": "images,location,urls",
        "limit": str(PAGE_LIMIT),
        "offset": str(offset),
        "lang": "en",
    }
    url = f"{API_URL}?{urllib.parse.urlencode(params)}"
    req = urllib.request.Request(url, headers={"x-windy-api-key": key})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)


def clean_title(title: str) -> str:
    """Windy titles look like 'Place › Direction: Name - Area'.
    The part after ':' is usually the cleanest human name."""
    if ":" in title:
        title = title.split(":", 1)[1].strip()
    return title


def transform(cam: dict) -> dict | None:
    loc = cam.get("location") or {}
    if loc.get("country_code") != "CH":
        return None
    if cam.get("status") != "active":
        return None
    images = (cam.get("images") or {}).get("current") or {}
    preview = images.get("preview")
    if not preview:
        return None
    return {
        "id": cam["webcamId"],
        "name": clean_title(cam.get("title", "")),
        "region": loc.get("region") or loc.get("city") or "",
        "city": loc.get("city") or "",
        "lat": loc.get("latitude"),
        "lon": loc.get("longitude"),
        "thumb": preview,
        "url": (cam.get("urls") or {}).get("detail")
            or f"https://windy.com/webcams/{cam['webcamId']}",
        "updated": cam.get("lastUpdatedOn"),
        "views": cam.get("viewCount", 0),
    }


def main() -> int:
    key = os.environ.get("WINDY_API_KEY")
    if not key:
        print("ERROR: WINDY_API_KEY env var not set", file=sys.stderr)
        return 1

    all_cams: list[dict] = []
    seen_ids: set[int] = set()
    for page in range(MAX_PAGES):
        offset = page * PAGE_LIMIT
        data = fetch_page(key, offset)
        webcams = data.get("webcams") or []
        if not webcams:
            break
        for cam in webcams:
            t = transform(cam)
            if t and t["id"] not in seen_ids:
                all_cams.append(t)
                seen_ids.add(t["id"])
        print(f"  page {page + 1}: +{len(webcams)} raw, "
              f"{len(all_cams)} kept total", file=sys.stderr)
        if len(webcams) < PAGE_LIMIT:
            break

    # Filter low-traffic cams, then sort by views (most-watched first).
    filtered = [c for c in all_cams if c["views"] >= MIN_VIEWS]
    filtered.sort(key=lambda c: c["views"], reverse=True)

    print(f"Fetched {len(all_cams)} active CH mountain cams; "
          f"{len(filtered)} above {MIN_VIEWS}-view threshold.",
          file=sys.stderr)

    js_payload = json.dumps(filtered, indent=2, ensure_ascii=False)
    OUTPUT.write_text(
        "// Auto-generated by scripts/fetch_windy_webcams.py — do not edit.\n"
        "// Source: Windy Webcams API v3 (https://api.windy.com)\n"
        f"window.WINDY_WEBCAMS = {js_payload};\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUTPUT.relative_to(Path.cwd()) if OUTPUT.is_relative_to(Path.cwd()) else OUTPUT}",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
