#!/usr/bin/env python3
"""Fetch Open-Meteo forecasts for all SAC peaks and write weather-cache.js."""

import json
import time
import urllib.parse
import urllib.request
from pathlib import Path

HIKES_ROOT = Path(__file__).resolve().parent.parent
SAC_ROUTES_JS = HIKES_ROOT / "guides" / "sac-routes.js"
OUTPUT = HIKES_ROOT / "command-center" / "weather-cache.js"

BATCH_SIZE = 40
DELAY_BETWEEN = 2.0
MAX_RETRIES = 3
FORECAST_DAYS = 5

BASE_URL = "https://api.open-meteo.com/v1/forecast"
DAILY_PARAMS = "weathercode,temperature_2m_max,temperature_2m_min,precipitation_sum,windspeed_10m_max,sunrise,sunset"
# MeteoSwiss ICON-CH2 — 2km grid, 5-day forecast horizon, alpine-tuned.
# (ICON-CH1 is 1km but only 33h horizon, too short for multi-day filtering.)
# Open-Meteo serves MeteoSwiss's own model output via a clean API.
MODEL = "meteoswiss_icon_ch2"


def load_sac_routes():
    text = SAC_ROUTES_JS.read_text(encoding="utf-8")
    json_str = text.split("=", 1)[1].strip().rstrip(";")
    return json.loads(json_str)


def unique_peaks(routes):
    seen = {}
    peaks = []
    for poi in routes:
        lat, lon = poi.get("lat"), poi.get("lon")
        if not lat or not lon:
            continue
        key = f"{lat:.3f},{lon:.3f}"
        if key in seen:
            continue
        seen[key] = True
        peaks.append({"lat": lat, "lon": lon, "alt": poi.get("alt", 0)})
    return peaks


def fetch_batch(peaks):
    lats = ",".join(f"{p['lat']:.4f}" for p in peaks)
    lons = ",".join(f"{p['lon']:.4f}" for p in peaks)

    params = urllib.parse.urlencode({
        "latitude": lats,
        "longitude": lons,
        "daily": DAILY_PARAMS,
        "timezone": "Europe/Zurich",
        "forecast_days": FORECAST_DAYS,
        "models": MODEL,
    })
    url = f"{BASE_URL}?{params}"

    last_err: Exception | None = None
    for attempt in range(MAX_RETRIES):
        try:
            req = urllib.request.Request(url)
            with urllib.request.urlopen(req, timeout=30) as resp:
                data = json.loads(resp.read().decode())
                return data if isinstance(data, list) else [data]
        except urllib.error.HTTPError as e:
            last_err = e
            if e.code == 429:
                wait = DELAY_BETWEEN * (2 ** (attempt + 1))
                print(f"  Rate limited, waiting {wait:.0f}s...")
                time.sleep(wait)
            else:
                raise
        except (urllib.error.URLError, TimeoutError) as e:
            last_err = e
            wait = DELAY_BETWEEN * (2 ** attempt)
            print(f"  Network error ({e}), waiting {wait:.0f}s before retry {attempt + 2}/{MAX_RETRIES}...")
            time.sleep(wait)
    print(f"  WARNING: batch failed after {MAX_RETRIES} retries ({last_err})")
    return None


def main():
    routes = load_sac_routes()
    peaks = unique_peaks(routes)
    print(f"Found {len(peaks)} unique peaks from {len(routes)} SAC routes")

    cache = {}
    batches = [peaks[i:i + BATCH_SIZE] for i in range(0, len(peaks), BATCH_SIZE)]

    for idx, batch in enumerate(batches):
        print(f"  Batch {idx + 1}/{len(batches)} ({len(batch)} peaks)...")
        results = fetch_batch(batch)
        if results:
            for i, loc in enumerate(results):
                peak = batch[i]
                key = f"{peak['lat']:.3f},{peak['lon']:.3f}"
                cache[key] = {
                    "elevation": loc.get("elevation"),
                    "daily": loc.get("daily"),
                }
        if idx < len(batches) - 1:
            time.sleep(DELAY_BETWEEN)

    print(f"Cached weather for {len(cache)} peaks")

    iso_now = time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())
    js = f"// Auto-generated by fetch_weather.py — {time.strftime('%Y-%m-%d %H:%M')}\n"
    js += f"window.WEATHER_CACHE_META = {{\"updated\":\"{iso_now}\",\"model\":\"{MODEL}\",\"peaks\":{len(cache)}}};\n"
    js += f"window.WEATHER_CACHE = {json.dumps(cache, separators=(',', ':'))};\n"
    OUTPUT.write_text(js, encoding="utf-8")
    size_kb = OUTPUT.stat().st_size / 1024
    print(f"Written to {OUTPUT} ({size_kb:.0f} KB)")


if __name__ == "__main__":
    main()
