// Auto-generated by scripts/fetch_slf_avalanche.py — do not edit.
// Source: SLF / WSL Institute for Snow and Avalanche Research.
// Endpoint: https://aws.slf.ch/api/bulletin/caaml/en/geojson
window.SLF_CACHE_META = {"updated": "2026-06-19T16:18:04Z", "publicationTime": null, "source": "https://aws.slf.ch/api/bulletin/caaml/en/geojson", "activeAt": null, "regionCount": 0};
window.SLF_CACHE = {"regions":[]};
