// Auto-generated by build_hike_gpx.py
// © OpenStreetMap contributors (ODbL); elevations © swisstopo / Open-Elevation
window.TRACK_FULL_COUNT = 7;
window.TRACK = [
[46.452694,7.878823,2507],
[46.453085,7.880414,2505],
[46.453438,7.882101,2501],
[46.453830,7.882726,2500],
[46.454234,7.883598,2507],
[46.455240,7.885304,2494],
[46.455360,7.885472,2496]
];
