// GENERATED FROM ../../templates/_assets/hike_map/slf_cache.js — edit the template, not this file.
// scripts/render_hike.py sync_assets() overwrites this on every `make render` (and on CI).

// Auto-generated by scripts/fetch_slf_avalanche.py — do not edit.
// Source: SLF / WSL Institute for Snow and Avalanche Research.
// Endpoint: https://aws.slf.ch/api/bulletin/caaml/en/geojson
window.SLF_CACHE_META = {"updated": "2026-06-19T18:05:44Z", "publicationTime": null, "source": "https://aws.slf.ch/api/bulletin/caaml/en/geojson", "activeAt": null, "regionCount": 0};
window.SLF_CACHE = {"regions":[]};
